<?php
	/***** DEFINED CONSTANTS *****/
	
	define('NOGDLIB','the necessary library (\'GD\') for image manipulation is not installed or not loaded');
	define('NOURL','the image url string was empty');
	define('NOIMAGE','there is no image to retrieve information from');
	define('NOMIME','image mime type unknown');
	define('NOWIDTH','image width unknown');
	define('NOHEIGHT','image height unknown');
	define('NODEPTH','image bit depth unknown');
	define('NOCHANNELS','number of channels in image unknown');
	define('NOTYPE','image type unknown');
	define('NOTTHUMBDIR','thumbnail directory is not a directory or does not exist');
	define('NODIR','directory cited is either not a directory or does not exist');
	define('NOIMGDATA','no image data');
	define('FAILEDSAVETHUMB','failed to save thumbnail to file');
	define('FAILEDSAVE','failed to save image to a file');
	define('FAILEDLOADIMAGE','failed to load image');
	define('FAILEDCROP','failed to crop image');
	define('FAILEDROTATE','failed to rotate image');
	define('FAILEDRESIZE','failed to resize image');
	define('FAILEDINFO','failed to retrieve image information');
	define('FAILEDTHUMB','failed to create thumbnail image');
	define('FAILEDTHMBSIZE','failed to set class object thumb size');
	define('INVALIDPARAM','invalid parameters for method');
	define('OUTOFBOUNDS','out of the image\'s boundaries');
?>