<?php

	/***** DEFINED CONSTANTS *****/
	define('NOIMAGEOBJECT','the image object was of the value NULL');
	define('NOIMAGELOADED','no image is loaded into the image object, cannot perform filter operation');
	define('FAILEDCOLORALLOCATION','failed allocate color during processing');
	define('FAILEDSETPIXEL','failed to set pixel color during processing');
	define('FAILEDFILTER','failed to perform filter operation');
	define('NODATA','no image data to work with');

?>